name: ATP
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.8.5
  - pip
  - pip:
      - numpy==1.24.4
      - pandas==1.2.3
      - Pillow==8.2.0
      - PyYAML==5.4.1
      - ftfy==6.0.3
      - regex==2021.7.1
      - dotmap==1.3.23
      - tqdm==4.67.1
      - torch==2.4.1
      - torchvision==0.19.1
      - wandb==0.21.1
      - opencv-python
